apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-config
  namespace: default
data:
  #EULA acceptance
  EULA: "TRUE"
  MOTD: "Dean Leon's Server 934513949"
  #JVM heap allocation
  MEMORY: "2G"
